spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_and_pickup
    username: postgres
    password: Sadiq2002
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      keepalive-time: 60000
      minimum-idle: 3
      maximum-pool-size: 4
      auto-commit: true
      connection-test-query: select 1
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            default_schema: public
        hibernate:
          ddl-auto: none
        show-sql: false
        defer-datasource-initialization: false
        open-in-view: false
      h2:
        console:
          enabled: true
      sql:
        init:
          mode: always
security:
  jwt:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw9RrcpBYzoogH5qneZ/46DkD034Zu1reQk9XCXQmreuLJ7p/0tc7AHWYE9thS+7kk7I7Sq2HL6HaQbU7csmjoNOLK0AzBNdF5NiR42ZxbMeLuhD+o6i4bQYBLsqgLpx1MPdAfHHLIAbkXZokQdCSAyf9jgvJmAQQvSVCy4quS1iJ55yhpuaKKRAH5orpqhuMU2UKd76gcfn3hPf7/6Gy04DNaqqo85W8w4mMNHRC6a9oAktOAuGq+GXM0TAPGiUFqQV0wd66Jm2xaIjtFwaAn27Rip1qmVbsK2V6pYGDDPlD4Ue0dzC7OELOIHqa/+SHPxXv/UTZRSuBTHLBHVSJ+wIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDD1GtykFjOiiAfmqd5n/joOQPTfhm7Wt5CT1cJdCat64snun/S1zsAdZgT22FL7uSTsjtKrYcvodpBtTtyyaOg04srQDME10Xk2JHjZnFsx4u6EP6jqLhtBgEuyqAunHUw90B8ccsgBuRdmiRB0JIDJ/2OC8mYBBC9JULLiq5LWInnnKGm5oopEAfmiumqG4xTZQp3vqBx+feE9/v/obLTgM1qqqjzlbzDiYw0dELpr2gCS04C4ar4ZczRMA8aJQWpBXTB3rombbFoiO0XBoCfbtGKnWqZVuwrZXqlgYMM+UPhR7R3MLs4Qs4gepr/5Ic/Fe/9RNlFK4FMcsEdVIn7AgMBAAECgf91a2kByIt3TFr2mETTKJiWpZkltva24EVkfS4y/PI0VoeZyrnaMjOuktQdE+3DGfr0lGn43ROx+9pii8iZi04RoMZRqKzuuiWukiznrQVVtFCTwJzuhLwQowkShWyGhkm+koKYG6MwEPHdLg+PZwAl5FSkV20JOWbQAweKBB1+DwvLX8y4h3BMjQwYmEFbD31QOUDV9vkTZzfRfbC/Obvh1/CCszXbFQ1ejxtPruYWLHmnGKsCjAdbKE47lQnGLDmIMj0wGoNW3ry6PkI3Q9JHpHI4tx5xHRij8dSa2a1SEq0DREml7pSLxsUY4AsOXfBnnFMcXKHVcSaS6nAbPe0CgYEA6zyk5uynnwG43yLdc8pGu5OvGYW79LzGYEJtVncmuqznVFWJ+mkmPSEjRMHBqyBZNTT/ydal8fHEsDtID28Vdt51fUNF1X4Rwhr8fV3GBY8q/pSYFJBk27qlpw9wI5dNGITzz84RG1JUvG9XmSh3R0SkkQzpH5BIwpmYGwK0EY0CgYEA1R1Xd9vi7Ruu+Pz6bMjKO7IDYWtkjZ7kt2limyE4SoZduzO/lW5t+/Zvfd3Iwd06k9Ity7V23QtSdSjbCeoVZZb+a5i1vmUClRTgrlUlvAf8kU/PZnNLObXkkMsiagPZNGPtqMNw9qh2TEYonDkj4HabhBgSxeN1iHhfNylWM6cCgYEAhFjyThoHlKZbZO8wuNytPwuwECP1w5QR6EZ3TZZr68sru38EyiYupWXned+pHqZsikrvPpfNdXoYty4jNMvCv8YZRAh9Wcg8JYEZXU9NAgOypNjlV2yF0joIyR0ecmfFsG3c3qWJal2/3uSl3D2wHiC4lgM1hdSfmxzfPxMeTGECgYEAgOBNlN4UTO8A0PGrPz3tjkwIX1FibYI5LfE9ADMGp4q6BAs3QFaXjFdq9OK6FQKD+gCQUTBbwTCnnNIoI8a7ScQV91tSDOFovl7xwHsdZqgtxHJPKdVvGGc24Zj2JsZNA7GqdvQ5y+/0GgwTYuXrHEKdqTQlpiX3XZ/tdJ460uECgYEAg2pog49sqpmTsJDMu5Q9Cc/jsUCvPzPBpjHsDQqMFXJtFrVToR304Lv6hLa/7dET5KSmUft3azmABgkxXFr7k6+2FO6w+FE38+Na5qkPQYim3cNxAAmYF68dOkuisf5OnTmwxcS7TTJE/7/R7koF8nS4zzyAChraGhEBm/49Gr0=
    access-token-validity-time: 1800000
    refresh-token-validity-time: 86400000