spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_and_pickup
    username: postgres
    password: Sadiq2002
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      keepalive-time: 60000
      minimum-idle: 3
      maximum-pool-size: 4
      auto-commit: true
      connection-test-query: select 1
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            default_schema: public
        hibernate:
          ddl-auto: none
        show-sql: false
        defer-datasource-initialization: false
        open-in-view: false
      h2:
        console:
          enabled: true
      sql:
        init:
          mode: always
security:
  jwt:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw4qqR9UmlgT1/prv4zJjbW5rh4Qw1Mr18R0QMkTx/BiWNZDxGfqghEgeHvlawLiXJoZ766oenCJU9HsdSwFnfo1Fquc6YM0p2mKE7EpaBnUWZpsU3DuvHbziV8TLZlJvbtNtpaNhMKoX9LaWp32EEYAxjtH6JHtoVqBY5KpRr9m9Gj8M1mAj95VSFaJl1y7ryuw3ENZjHJtjtlQUKCDvgh7Httxh8dTAx5aRzokjVwhMMSKpljboqruLUXTPW1HFQ/CttMRetm4XJNEIBqauARRv3d5JCOLVCiv6lrL4trdcYoQNKCuGeYwHT9hvw4yS6EB9ZzRT2nHn6O2jtlQxRQIDAQAB
    private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDDiqpH1SaWBPX+mu/jMmNtbmuHhDDUyvXxHRAyRPH8GJY1kPEZ+qCESB4e+VrAuJcmhnvrqh6cIlT0ex1LAWd+jUWq5zpgzSnaYoTsSloGdRZmmxTcO68dvOJXxMtmUm9u022lo2Ewqhf0tpanfYQRgDGO0foke2hWoFjkqlGv2b0aPwzWYCP3lVIVomXXLuvK7DcQ1mMcm2O2VBQoIO+CHse23GHx1MDHlpHOiSNXCEwxIqmWNuiqu4tRdM9bUcVD8K20xF62bhck0QgGpq4BFG/d3kkI4tUKK/qWsvi2t1xihA0oK4Z5jAdP2G/DjJLoQH1nNFPacefo7aO2VDFFAgMBAAECggEASlRbhhKwKDaai725klOFGAPxPAIzza+Y7Z5uma07juiJsLL38zgh7Ca9zGhc5wVD75EPafWwzQj/4i8qY2iVPrXU1bIvrrxOPIVWobthnTLE4RvyQgUt+8/g+hwEdVDAqxATjfMc7rK5iHwfqGs92KkyLWgD/forH0K0h7d2dbFUU2vnhv2U0DwfzMdaMNst93gwHh2/kuufHRAq0pq/4VXqk9SFCjn1RupI4Qngx3WMkL/yTACk0UgDdBSgJL/LcZDupl7fRYxN5UM9PGvbId0tEBmGV2CJCVtCtiwCCLYwBXg0PNYEkVi5h+3kVHQGIElFr3Q49zZe2WmgE3P7wQKBgQDy+vseT3+82v5NUTwxbT/vC0/fk51MfGc110rVbtSSCiPI4mIXk5qa1bJngLx5Agk/5Fe7O1AKFGuFo1ZqnaBmeHB+44dPAWwM7TDupUD4p6+5HL78D8/A7/AtyKjijCrvTCpFgXkNIxgXzHgryqRt3aZsD+ZceolxnaVAUYVhawKBgQDOBPS72yu/65Vfw4Du8dpIWpgnP+qvMxRC09zvcgw3XR7hdpqXAAaGnThZikb5Z1idasC0r4waFkNQM7VJWeQseANjBwdnIeYNp2shcMJc6lNL6QIh4s6tEx6S6isM6QZ/4Cwi2g4KcZwbPepAVLsmT/4jLEoZIJ0Yk95nst10DwKBgHhIjKXNnyOjmX4298BUH/E7PVgloBnr/7/kizQrQGnnQR3CC+M1+7Qok7+vOB4DRwbtCA006IOE5lFqsW3oCC6R8sat5h7TSmT/ylhpUEeH43KU62qmfSc64EAZ9Jjp4JtDri1oUb+SHuwxGVA8abfFoQwftt8S/hVTgCnd8VRvAoGAZOB0XU+yGmVmXN/D0DxIX8lMW1umtGbUcux+cBht9uX36vpCM9HlYCC3qNBWdGSwNVRCS7bxaQyhpTHMgMAtQ8D4F5Mngs5McT8a6+LkqM5sPu03CBSgkoqcG9/heI7Zid/gfKg828xJXeVxQFK82MOuctaK6cbYZWJyMmCYou0CgYBUPj16kLBWamZzuIWSpqFnV8+xjI0+8YwPHtLOZ9fQtvlBmzyg9XgSvXky2dV8t/okHzpypHgP4ciMK4tfFji/FDM8YLEsnErUWsOLRTDVdDJreLJx4cEeQUcT/bj5xCwz5s9ikwTiXt0b/+gLofOgyDEP9EJLFrihj7rqtp3ctA==
    access-token-validity-time: 1800000
    refresh-token-validity-time: 86400000