package delivery_and_pickup_system.delivery_and_pickup_system.service.proof_of_delivery;

import delivery_and_pickup_system.delivery_and_pickup_system.model.dto.proof_of_elivery.ProofOfDeliveryRequestDTO;
import delivery_and_pickup_system.delivery_and_pickup_system.model.dto.proof_of_elivery.ProofOfDeliveryResponseDTO;

public interface ProofOfDeliveryService {
    ProofOfDeliveryResponseDTO createProof(ProofOfDeliveryRequestDTO dto);

    ProofOfDeliveryResponseDTO getProofByShipmentId(Integer shipmentId);
}